Dataset #1: List of best-selling video games from Wikepedia data cleanup & Analysis

In [2]:
import pandas as pd

In [61]:
df = pd.read_csv("videogame1_tidy.csv")

The first analysis determine which video games have sold the most copies globally, the dataset is sorted by the Global_Sales_Millions column in descending order. The head(10) function is then used to display the top 10 highest-selling games in the dataset.

In [62]:
df.sort_values("Global_Sales_Millions", ascending=False).head(10)

,Rank,Title,Global_Sales_Millions,Series,Platform(s),Release_Year,Developer(s),Publisher(s)
0,1.0,Tetris,520.00,NaN,Multi-platform,1988[c],Various,Various
1,1.0,Minecraft,350.00,Minecraft,Multi-platform,2011[d],Mojang Studios,Mojang Studios
2,2.0,Grand Theft Auto V,225.00,Grand Theft Auto,Multi-platform,2013,Rockstar North,Rockstar Games
3,3.0,Wii Sports?,82.90,Wii,Wii,2006,Nintendo EAD,Nintendo
4,4.0,Red Dead Redemption 2,82.00,Red Dead,Multi-platform,2018,Rockstar Games,Rockstar Games
5,5.0,Mario Kart 8 / Deluxe,79.05,Mario Kart,Wii U / Switch,2014,Nintendo EAD / Nintendo EPD (Deluxe),Nintendo
6,6.0,PUBG: Battlegrounds,75.00,PUBG Universe,Multi-platform,2017,PUBG Studios,Krafton
7,7.0,Terraria,64.00,NaN,Multi-platform,2011,Re-Logic,Re-Logic / 505 Games
8,8.0,The Witcher 3: Wild Hunt,60.00,The Witcher,Multi-platform,2015,CD Projekt Red,CD Projekt
9,9.0,Super Mario Bros.?,58.00,Super Mario,Multi-platform,1985,Nintendo R&D4,Nintendo

The next analysis shows which publishers have generated the most game sales, the dataset is grouped by the Publisher. The total global sales for each publisher are then calculated by summing the Global_Sales_Millions column.

In [65]:
df.groupby("Publisher(s)")["Global_Sales_Millions"].sum().sort_values(ascending=False)

Publisher(s)
Nintendo                          681.64
Various                           520.00
Rockstar Games                    359.50
Mojang Studios                    350.00
Activision                        166.70
Nintendo / The Pokémon Company    106.25
CD Projekt                         95.00
Electronic Arts                    77.00
Krafton                            75.00
Re-Logic / 505 Games               64.00
Curve Digital                      55.00
Blizzard Entertainment             50.00
Chucklefish / ConcernedApe         50.00
505 Games                          40.00
Sega                               40.00
Warner Bros. Games                 40.00
2K Games                           30.00
Bandai Namco                       30.00
Bethesda Softworks                 30.00
Capcom                             29.10
Game Science                       28.00
Sony Computer Entertainment        26.60
Sony Interactive Entertainment     26.10
Valve                              25.56
Kinetic Games                      25.00
Name: Global_Sales_Millions, dtype: float64

The last analysis highlights how many best-selling games appear on each gaming platform. The value_counts() function counts how frequently each platform appears in the Platform(s) column, helping identify the most common platforms among top-selling games.

In [64]:
df["Platform(s)"].value_counts()

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

Platform(s)
Multi-platform     32
Wii                 6
Nintendo Switch     5
Nintendo DS         2
Wii U / Switch      1
Game Boy Color      1
Famicom / NES       1
PS3 / PS4           1
Multi-Platform      1
Nintendo 3DS        1
PC                  1
Name: count, dtype: int64

Overall, each analysis highlights reveail insights into the best-selling video games, the publishers responsible for the highest sales, and the platforms that host the most successful titles. Sorting the dataset helps identify the most popular games, grouping by publishers highlights the companies with the greatest market success, and counting platforms shows which gaming systems are most associated with top-selling titles.

Dataset #2: NBA Scoring Statistics Data Clean-Up & Analysis

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("clean_nbadata.csv")
df.head()

,Player,Team,Age,GP,W,L,Min,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,PF,FP,DD2,TD3,PlusMinus
0,Tyrese Maxey,PHI,25,60,33,27,2295.9,1736,604,1314,...,249,402,144,120,50,129,3004,7,0,96
1,Shai Gilgeous-Alexander,OKC,27,52,41,11,1728.7,1645,565,1027,...,228,335,109,71,40,106,2645,5,0,589
2,Jaylen Brown,BOS,29,55,35,20,1884.0,1588,586,1220,...,396,276,197,54,24,149,2514,13,3,168
3,Luka Dončić,LAL,27,49,31,18,1735.8,1586,506,1070,...,378,421,198,68,25,118,2752,28,6,69
4,Donovan Mitchell,CLE,29,55,35,20,1840.1,1570,546,1131,...,247,320,170,86,15,132,2479,4,0,357

The first analysis identifies the players who scored the most total points in the dataset. 
By sorting the dataset by the **PTS (points)** column in descending order, we can determine 
which players contributed the most offensively.

In [5]:
top_scorers = df.sort_values(by="PTS", ascending=False).head(10)

top_scorers[["Player", "Team", "PTS"]]

                    Player Team   PTS
0             Tyrese Maxey  PHI  1736
1  Shai Gilgeous-Alexander  OKC  1645
2             Jaylen Brown  BOS  1588
3              Luka Dončić  LAL  1586
4         Donovan Mitchell  CLE  1570
5          Anthony Edwards  MIN  1543
6            Jalen Brunson  NYK  1536
7             Kevin Durant  HOU  1497
8             Jamal Murray  DEN  1463
9          Cade Cunningham  DET  1360

The second analysis focuses on passing ability by identifying the players with the highest number of assists. Assists are an important statistic because they measure a player’s ability to create scoring opportunities for their team.

In [6]:
top_assists = df.sort_values(by="AST", ascending=False).head(10)

top_assists[["Player", "Team", "AST"]]

               Player Team  AST
9     Cade Cunningham  DET  533
11       Nikola Jokić  DEN  476
15      Jalen Johnson  ATL  446
14       James Harden  CLE  429
3         Luka Dončić  LAL  421
8        Jamal Murray  DEN  415
0        Tyrese Maxey  PHI  402
40        LaMelo Ball  CHA  388
6       Jalen Brunson  NYK  367
43  Immanuel Quickley  TOR  354

The third analysis examines scoring performance at the team level. Using the groupby() function in pandas, the dataset is grouped by team and the average number of points scored by players on each team is calculated.

In [9]:
team_scoring = df.groupby("Team")["PTS"].mean().sort_values(ascending=False)

team_scoring

Team
PHI    1736.000000
OKC    1645.000000
LAL    1586.000000
MIN    1439.500000
CLE    1430.000000
DEN    1390.500000
DET    1360.000000
LAC    1309.000000
IND    1270.000000
NYK    1228.666667
BOS    1218.333333
HOU    1196.666667
BKN    1183.000000
ATL    1182.000000
UTA    1173.500000
ORL    1162.500000
SAC    1147.000000
TOR    1142.000000
POR    1099.000000
CHA    1075.333333
PHX    1074.500000
GSW    1061.000000
MIA    1056.000000
NOP    1048.666667
SAS    1035.000000
DAL     999.000000
MIL     989.000000
Name: PTS, dtype: float64

After cleaning and transforming the dataset, several insights were discovered through  analysis of player statistics. The dataset revealed the top scoring players, the leading  playmakers based on assists, and the teams with the highest average scoring output.

Dataset #3: Box Office Mojo Clean Up & Analysis

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("boxoffice_yearly_clean.csv")

df.head()

,Year,Total_Gross,Percent_Change,Releases,Average_Gross,Top_Movie
0,2026,1163425613,NaN,165,7051064,Avatar: Fire and Ash
1,2025,8655387700,1.0,668,12957167,A Minecraft Movie
2,2024,8571249443,-3.8,677,12660634,Inside Out 2
3,2023,8907716802,20.9,592,15046818,Barbie
4,2022,7369914732,64.4,502,14681105,Top Gun: Maverick

The first analysis identifies the years with the highest total box office revenue. Sorting the dataset by total gross revenue reveals which years were the most successful financially for the film industry.

In [3]:
highest_gross = df.sort_values(by="Total_Gross", ascending=False).head(5)

highest_gross[["Year","Total_Gross","Top_Movie"]]

    Year  Total_Gross                 Top_Movie
8   2018  11892160011             Black Panther
10  2016  11375225455              Finding Dory
7   2019  11363360766         Avengers: Endgame
11  2015  11148780747            Jurassic World
9   2017  11075387520  Star Wars: The Last Jedi

The second analysis shows which years had the highest number of movie releases. Examining the number of releases helps determine trends in film production over time.

In [4]:
most_releases = df.sort_values(by="Releases", ascending=False).head(5)

most_releases[["Year","Releases"]]

    Year  Releases
8   2018       993
7   2019       910
10  2016       855
9   2017       854
12  2014       849

The third analysis evaluates which years had the highest average revenue per movie. This metric provides insight into how profitable movies were on average in a given year.

In [5]:
avg_gross = df.sort_values(by="Average_Gross", ascending=False)

avg_gross[["Year","Average_Gross"]].head(10)

    Year  Average_Gross
3   2023       15046818
4   2022       14681105
14  2012       13436978
10  2016       13304357
13  2013       13263347
11  2015       13193823
9   2017       12968837
1   2025       12957167
2   2024       12660634
7   2019       12487209

After cleaning and analyzing the dataset, several trends in the film industry became highlighted. The analysis identified the years with the highest overall box office revenue, the years with the greatest number of film releases, and the years with the highest average revenue per movie. Using pandas made it possible to efficiently organize and analyze the data, demonstrating the importance of properly structured datasets for meaningful analysis.